name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: windows-latest
            name: windows
            ext: ".exe"
          - os: macos-latest
            name: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build
        run: go build -o exp-track${{ matrix.ext }} main.go

      - name: Create archive
        run: |
          mkdir release
          cp exp-track${{ matrix.ext }} release/
          tar -czf exp-track-${{ matrix.name }}.tar.gz release/*
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: exp-track-${{ matrix.name }}
          path: exp-track-${{ matrix.name }}.tar.gz

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List files in artifacts
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/exp-track-linux/exp-track-linux.tar.gz
            artifacts/exp-track-windows/exp-track-windows.tar.gz
            artifacts/exp-track-darwin/exp-track-darwin.tar.gz
